### ISSUE TITLE
Crash on Tab switch? 

### ISSUE THREAD

**Issue by goforbg** [MindorksOpenSource/Jetpack-Compose-WhatsApp-Clone#1]
Running this on the latest canary build of Android studio just to check-out the project, with Nexus 5 API 27 emulator. Not sure why the crash happens, can anybody take a look? 

`2020-05-09 11:02:02.060 4265-4265/com.mindorks.sample.whatsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mindorks.sample.whatsapp, PID: 4265
    java.lang.IllegalStateException: LayoutCoordinate operations are only valid when isAttached is true
        at androidx.ui.core.LayoutNodeWrapper.localToRoot(LayoutNodeWrapper.kt:180)
        at androidx.ui.core.LayoutNodeWrapper.localToGlobal(LayoutNodeWrapper.kt:176)
        at androidx.ui.core.pointerinput.PointerInputFilter.getPosition$ui_platform_release(PointerInput.kt:100)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:333)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.Node.dispatchChanges(HitPathTracker.kt:339)
        at androidx.ui.core.pointerinput.NodeParent.dispatchChanges(HitPathTracker.kt:201)
        at androidx.ui.core.pointerinput.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
        at androidx.ui.core.pointerinput.HitPathTracker.dispatchChanges$default(HitPathTracker.kt:93)
        at androidx.ui.core.pointerinput.PointerInputEventProcessor.process(PointerInputEventProcessor.kt:77)
        at androidx.ui.core.AndroidComposeView.dispatchTouchEvent(AndroidOwner.kt:641)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
        at android.view.View.dispatchPointerEvent(View.java:12015)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6735)
`

**Comment by hi-manshu** [comment]
Can you tell me the version of AS ? is it 4.1 preview?

**Comment by goforbg** [comment]
> Can you tell me the version of AS ? is it 4.1 preview?

Android Studio 4.1 Canary 9
Build #AI-201.3803.71.41.6466190, built on May 6, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins:

**Comment by hi-manshu** [comment]
It is fixed in the latest push.
